import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://www.paloaltoadvanceddentists.com'
  const lastModified = new Date()

  return [
    { url: base,                                     lastModified, changeFrequency: 'monthly', priority: 1.0 },
    { url: `${base}/services`,                       lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/services/implants`,              lastModified, changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/services/pinhole`,               lastModified, changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/services/smile-makeover`,        lastModified, changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/services/invisalign`,            lastModified, changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/services/dental-emergencies`,    lastModified, changeFrequency: 'monthly', priority: 0.95 },
    { url: `${base}/services/periodontics`,          lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/services/teeth-whitening`,       lastModified, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/services/cleanings`,             lastModified, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/doctors`,                        lastModified, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/practice`,                       lastModified, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/patients`,                       lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/contact`,                        lastModified, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/services/bone-grafting`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/braces`,                lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/braces-for-children`,   lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/bruxism`,               lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/crown-lengthening`,     lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/dental-bridges`,        lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/dental-crowns`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/dentures`,              lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/digital-xrays`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/gum-disease`,           lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/gum-disease-and-diabetes`,      lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/gum-disease-and-heart-disease`, lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/gum-grafting`,          lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/gum-recession`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/inlays-onlays`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/invisalign-faqs`,       lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/mini-implants`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/oral-cancer-exam`,      lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/orthodontic-conditions`,        lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/pediatric-dentistry`,   lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/pediatric-sealants`,    lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/periodontal-scaling`,   lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/porcelain-veneers`,     lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/regenerative-procedures`,       lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/root-canal`,            lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/sinus-augmentation`,    lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/tmj-treatment`,         lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/tooth-extraction`,      lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/services/what-is-periodontal-disease`,   lastModified, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${base}/summer-smile-promo`,             lastModified, changeFrequency: 'monthly', priority: 0.5 },
  ]
}
